# https://docs.travis-ci.com/user/job-lifecycle

language: minimal

dist: focal

git:
  depth: 5

before_install:
- sudo apt-get -y install squirrel3

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - squirrel -c vscripts/confogl.nut
    - stage: test
      script:
        - ./test.sh
